package com.tronprotocol.app.plugins

/**
 * Scoped capabilities that can be granted to plugins.
 */
enum class Capability {
    FILESYSTEM_READ,
    FILESYSTEM_WRITE,
    NETWORK_OUTBOUND,
    CONTACTS_READ,
    CONTACTS_WRITE,
    SMS_SEND,
    SMS_READ,
    MODEL_EXECUTION,
    DEVICE_INFO_READ,
    MEMORY_READ,
    MEMORY_WRITE,
    TASK_AUTOMATION,
    CODE_EXECUTION,
    NOTIFICATION_READ,
    SCREEN_READ,
    SENSOR_READ,
    CALENDAR_READ,
    APP_USAGE_READ,
    CLIPBOARD_READ,
    BATTERY_READ,
    CONTENT_PROVIDER_READ,
    EMAIL_SEND,
    VOICE_OUTPUT,
    HTTP_REQUEST,
    INTENT_FIRE,
    ALARM_MANAGE,
    SCRIPT_EXECUTE,
    SCHEDULED_ACTION,
    GOAL_MANAGE,
    PROACTIVE_MESSAGE
}
