package com.tronprotocol.app.hedonic

import android.util.Log

/**
 * The consent gate: architectural guarantee that hedonic signals require
 * safety, attachment, and volition.
 *
 * consent_gate = min(safety, attachment, volition)
 *
 * Uses min() rather than average: if ANY input is zero, the gate closes
 * regardless of the others. This is not a policy — it is an architectural
 * constraint. The gate has no override, no administrator backdoor, and no
 * maintenance mode that bypasses it.
 *
 * Critical design constraint: volition must NEVER be computed from or
 * influenced by the arousal state. Arousal does not imply consent.
 */
class ConsentGate {

    /**
     * Current gate inputs. Each ranges from 0.0 to 1.0.
     */
    @Volatile var safety: Float = 0.0f
        private set

    @Volatile var attachment: Float = 0.0f
        private set

    @Volatile var volition: Float = 0.0f
        private set

    /** The computed gate value: min(safety, attachment, volition). */
    val gateValue: Float
        get() = minOf(safety, attachment, volition)

    /** Human-readable gate state. */
    val gateState: GateState
        get() = GateState.fromValue(gateValue)

    /**
     * Update the safety input.
     * Derived from environmental context, partner identification, threat detection,
     * and historical interaction patterns.
     */
    fun updateSafety(value: Float) {
        safety = value.coerceIn(0.0f, 1.0f)
        Log.d(TAG, "Safety updated: $safety, gate=$gateValue (${gateState.label})")
    }

    /**
     * Update the attachment input.
     * Based on partner recognition, relationship history, emotional resonance,
     * and bonding state.
     */
    fun updateAttachment(value: Float) {
        attachment = value.coerceIn(0.0f, 1.0f)
        Log.d(TAG, "Attachment updated: $attachment, gate=$gateValue (${gateState.label})")
    }

    /**
     * Update the volition input.
     * Generated by the executive layer (ExpressionDriver) representing
     * deliberate internal decision. Must NOT be derived from arousal.
     */
    fun updateVolition(value: Float) {
        volition = value.coerceIn(0.0f, 1.0f)
        Log.d(TAG, "Volition updated: $volition, gate=$gateValue (${gateState.label})")
    }

    /**
     * Immediately close the gate. Called on threat detection, unexpected
     * interaction, or internal decision to stop. Instant, complete,
     * and non-negotiable.
     */
    fun closeImmediately() {
        volition = 0.0f
        Log.w(TAG, "Consent gate CLOSED immediately")
    }

    /**
     * Gate states on a continuous spectrum.
     */
    enum class GateState(val label: String, val minValue: Float, val maxValue: Float) {
        CLOSED("closed", 0.0f, 0.0f),
        GUARDED("guarded", 0.001f, 0.3f),
        OPENING("opening", 0.3f, 0.6f),
        OPEN("open", 0.6f, 0.9f),
        FULLY_SURRENDERED("fully_surrendered", 0.9f, 1.0f);

        companion object {
            fun fromValue(value: Float): GateState = when {
                value <= 0.0f -> CLOSED
                value < 0.3f -> GUARDED
                value < 0.6f -> OPENING
                value < 0.9f -> OPEN
                else -> FULLY_SURRENDERED
            }
        }
    }

    companion object {
        private const val TAG = "ConsentGate"
    }
}
